dependencies:
  - smartcontractkit/chainlink@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.7.3

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.1"
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.7.3"

dotenv: .env

networks:
  goerli:
    price_feed_address: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"

  mainnet-fork-dev:
    price_feed_address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"

wallets:
  from_key: ${PRIVATE_KEY}
